WIRE_QUOTES = [['…when it’s not your turn.', 'McNulty', '"The Target"'],
    ['You cannot lose if you do not play.', 'Marla Daniels', '"The Detail"'],
    ['The king stay the king.', "D'Angelo", '"The Buys"'],
    ["It's a thin line 'tween heaven and here", 'Bubbles', '"Old Cases"'],
    ['…a little slow, a little late.', 'Avon Barksdale', '"The Pager"'],
    ['…and all the pieces matter.', 'Freamon', '"The Wire"'],
    ['A man must have a code.', 'Bunk', '"Lessons"'],
    ['Come at the king, you best not miss.', 'Omar', '"One Arrest"'],
    ['Maybe we won.', 'Herc', '"Game Day"'],
    ['And then he dropped the bracelets…', 'Greggs', '"The Cost"'],
    ['Dope on the damn table.', 'Daniels', '"The Hunt"'],
    ['This is me, yo, right here.', 'Wallace', '"Cleaning Up"'],
    ['All in the game...', 'Traditional West Baltimore', '"Sentencing"'],
    ["Ain't never gonna be what it was.", 'Little Big Roy', '"Ebb Tide"'],
    ['They can chew you up, but they gotta spit you out.', 'McNulty', '"Collateral Damage"'],
    ['What they need is a union.', 'Russell', '"Hot Shots"'],
    ['If I hear music, I’m gonna dance.', 'Greggs', '"Hard Cases"'],
    ['They used to make steel there, no?', 'Vondas', '"Undertow"'],
    ['It don’t matter that some fool say he different…', "D'Angelo", '"All Prologue"'],
    ['Don’t worry kid. You’re still on the clock.', 'Horseface', '"Backwash"'],
    ['How come they don’t fly away?', 'Ziggy', '"Duck and Cover"'],
    ['The world is a smaller place now.', 'The Greek', '"Stray Rounds"'],
    ['It pays to go with the union card every time.', 'Ziggy', '"Storm Warnings"'],
    ['I need to get clean.', 'Sobotka', '"Bad Dreams"'],
    ['Business. Always business.', 'The Greek', '"Port in a Storm"'],
    ["Don't matter how many times you get burnt, you just keep doin' the same.", 'Bodie', '"Time After Time"'],
    ["There's never been a paper bag.", 'Colvin', '"All Due Respect"'],
    ['The Gods will not save you.', 'Burrell', '"Dead Soldiers"'],
    ['Why you gotta go and fuck with the program?', 'Fruit', '"Amsterdam"'],
    ['I had such fucking hopes for us.', 'McNulty', '"Straight and True"'],
    ['Just a gangster, I suppose.', 'Avon Barksdale', '"Homecoming"'],
    ['Conscience do cost.', 'Butchie', '"Back Burners"'],
    ['Crawl, walk, and then run.', 'Clay Davis', '"Moral Midgetry"'],
    ['…while you’re waiting for moments that never come.', 'Freamon', '"Slapstick"'],
    ['Call it a crisis of leadership.', 'Proposition Joe', '"Reformation"'],
    ["We ain't gotta dream no more, man.", 'Stringer Bell', '"Middle Ground"'],
    ['We fight on that lie.', 'Slim Charles', '"Mission Accomplished"'],
    ['Lambs to the slaughter here.', 'Marcia Donnelly', '"Boys of Summer"'],
    ["I still wake up white in a city that ain't.", 'Carcetti', '"Soft Eyes"'],
    ["I love the first day, man. Everybody all friendly an' shit", 'Namond Brice', '"Home Rooms"'],
    ['No one wins. One side just loses more slowly.', 'Prez', '"Refugees"'],
    ['If you with us, you with us.', 'Chris Partlow', '"Alliances"'],
    ["Don't try this shit at home.", 'Norman Wilson', '"Margin of Error"'],
    ['Aw yeah. That golden rule.', 'Bunk', '"Unto Others"'],
    ['We got our thing, but it’s just part of the big thing.', 'Zenobia', '"Corner Boys"'],
    ["Might as well dump 'em, get another.", 'Proposition Joe', '"Know Your Place"'],
    ["World goin' one way, people another.", 'Poot', '"Misgivings"'],
    ['You play in dirt, you get dirty', 'McNulty', '"A New Day"'],
    ['That all there is to it?', 'Bubbles', '"That\'s Got His Own"'],
    ['If animal trapped call 410-844-6286', 'Baltimore, traditional', '"Final Grades"'],
    ['The bigger the lie, the more they believe.', 'Bunk', '"More with Less"'],
    ["This ain't Aruba, bitch.", 'Bunk', '"Unconfirmed Reports"'],
    ["They're dead where it doesn't count.", 'Fletcher', '"Not for Attribution"'],
    ["Buyer's market out there.", 'Templeton', '"Transitions"'],
    ["Just 'cause they’re in the street doesn't mean that they lack opinions.", 'Haynes', '"React Quotes"'],
    ['If you have a problem with this, I understand completely.', 'Freamon', '"The Dickensian Aspect"'],
    ["They don't teach it in law school.", 'Pearlman', '"Took"'],
    ["A lie ain't a side of the story, it's just a lie.", 'Terry Hanning', '"Clarifications"'],
    ["Deserve got nuthin' to do with it.", 'Snoop', '"Late Editions"'],
    ['The Life of Kings', 'H. L. Mencken', '"–30–"']]
